### ISSUE TITLE
Does OO model the real world?

### ISSUE THREAD

**Issue by pletcher** [learn-co-curriculum/ruby-intro-to-object-relationships-with-belongs-to#7]
I'm not convinced that this is the case, nor am I convinced that it's even desirable.

**Comment by AnnJohn** [comment]
@pletcher how should @StevenNunez change this? Thanks!

**Comment by pletcher** [comment]
Sorry to get you wrapped up in my rant against OO as a representation of the real world, @StevenNunez and @AnnJohn. 

To expand on stuff I mentioned previously, I think harping on real-world analogies in OO is expedient starting out, but is ultimately confusing and makes it harder for students to spot useful abstractions. I know that I'm fighting an uphill battle here, but I would love it if we could find a simple way to shift the conversation from modeling the real world to grouping related actions and properties (which, as far as I can tell, is really what OO is about)

**Comment by octosteve** [comment]
@pletcher 

> Building an object-oriented application means inventing appropriate machinery. We represent real-world information, processes, interactions, relationships, even errors, by inventing objects that don't exist in the real world. We give life and intelligence to inanimate things. We take difficult-to-comprehend real-world objects and split them into simpler, more manageable software ones. We invent new objects. Each has a specific role to play in the application. **Our measure of success lies in how clearly we invent a software reality that satisfies our application's requirements -- and not in how closely it remembers the real world.**
> -- Rebecca Wirfs-Brock, Object Design

I'm with you. I think we need to start having a conversation about what those 'made up' objects are. A connection, a procedure, an adapter...

**Comment by pletcher** [comment]
:heart:

**Comment by pletcher** [comment]
Yeah -- the thing that I'm struggling with is how to introduce this to beginners :/

**Comment by octosteve** [comment]
I think there might be a separate readme on "What are objects? Spotting Objects in the wild". @pletcher

**Comment by pletcher** [comment]
That would be a super interesting README -- do you think it could fit nicely with current materials?

**Comment by JeffKatzy** [comment]
love the quote - changed model to reflect.
