### ISSUE TITLE
The beginning is a bit dense

### ISSUE THREAD

**Issue by pletcher** [learn-co-curriculum/ruby-intro-to-object-relationships-with-belongs-to#8]

**Comment by AnnJohn** [comment]
@pletcher do you have any specifics or suggestions for @StevenNunez to edit this? thanks

**Comment by pletcher** [comment]
I would love to see the intro broken up so that examples are fleshed out, e.g., "For example, a Dog class might have methods that describe an individual dog's attributes and behaviors. A single dog could have a name (as a Ruby String) and tell you their name but not have it play with another dog object." could looke like

``` ruby
class Dog
  def initialize(name, size, temperament)
    @name = name
    @size = size
    @temperament = temperament
  end

  def bark
    if @temperament != 'quiet'
      puts "RUFF!"
    else
      puts "rf"
    end
  end
end
```

Or something.
